
```{r}
#rm(list = ls())
library("BSDA")
library(ggplot2)
library("ggpubr")
library(dplyr)
```




#Hybrid one-stage function
```{r}
hybrid_one_stage=function(sigma1, sigma2, tau1,tau2, theta,  mu_t, mu_c, pi,k, c1,c2,
                          r, lambda,alpha, beta,  test, nsim, seed_number){
  
  #------------------------------------
  z_a=qnorm(1-alpha)
  #z_a
  z_b=qnorm(1-beta)
  #z_b

  n1=(4*(tau1^2)*((z_a+z_b)^2))/((theta^2)*(1+ (((1+pi)^2)*r/(k) ) ))
  
  
  #n1
  n2=r*n1
  #n2
  n1=2*ceiling(n1/2)
  n2=2*ceiling(n2/2)
  
  cost_val=n1*c1+n2*c2
  n_val=n1+n2
  
  #-------------------------------
  
  sig_vec=c()
  
  
  
  final_result=list(n1=n1,
                    n2=n2,
                    n=n_val
  )
  
  return(final_result)
  
  
}
```




#k=1.5, pi=0
```{r}
#lower back pain rho=0.3
n1_vec=c()
n2_vec=c()
n3_vec=c()
n4_vec=c()
n5_vec=c()
n6_vec=c()
n7_vec=c()
n8_vec=c()
n9_vec=c()
n10_vec=c()
n11_vec=c()
n12_vec=c()
n13_vec=c()
n14_vec=c()
n15_vec=c()
ind=seq(0.3,0.7, by=0.1)
for (i in ind) {
  res1=hybrid_one_stage(sigma1=20, sigma2=24, tau1=20, tau2=24,
                         theta=20*i,  mu_t=30, mu_c=20, pi=0, k=1.5,
                         c1=1200, c2=300,
                         r=1, lambda=1, 
                         alpha=0.025, beta=0.2,  
                         test="z_score", nsim=1, seed_number=13487)
  
  res2=hybrid_one_stage(sigma1=20, sigma2=24, tau1=20, tau2=24,
                         theta=20*i,  mu_t=30, mu_c=20, pi=0, k=1.5,
                         c1=1200, c2=300,
                         r=1.5, lambda=1, 
                         alpha=0.025, beta=0.2,  
                         test="z_score", nsim=1, seed_number=13487)
  
  res3=hybrid_one_stage(sigma1=20, sigma2=24, tau1=20, tau2=24,
                         theta=20*i,  mu_t=30, mu_c=20, pi=0, k=1.5,
                         c1=1200, c2=300,
                         r=2, lambda=1, 
                         alpha=0.025, beta=0.2,  
                         test="z_score", nsim=1, seed_number=13487)
  
  res4=hybrid_one_stage(sigma1=20, sigma2=24, tau1=20, tau2=24,
                         theta=20*i,  mu_t=30, mu_c=20, pi=0, k=1.5,
                         c1=1200, c2=300,
                         r=2.5, lambda=1, 
                         alpha=0.025, beta=0.2,  
                         test="z_score", nsim=1, seed_number=13487)
  
  res5=hybrid_one_stage(sigma1=20, sigma2=24, tau1=20, tau2=24,
                         theta=20*i,  mu_t=30, mu_c=20, pi=0, k=1.5,
                         c1=1200, c2=300,
                         r=3, lambda=1, 
                         alpha=0.025, beta=0.2,  
                         test="z_score", nsim=1, seed_number=13487)

  n1_vec=c(n1_vec,res1$n)
  n2_vec=c(n2_vec,res2$n)
  n3_vec=c(n3_vec,res3$n)
  n4_vec=c(n4_vec,res4$n)
  n5_vec=c(n5_vec,res5$n)

  
  
}

N_vec_cs = c(n1_vec, n3_vec,   n5_vec)

```


```{r}


val = N_vec_cs
efs = rep(seq(0.3,0.7,0.1),3)
ra = rep(c("r=1", "r=2", "r=3"), each=5)

dat=data.frame(value=val, quantity=efs, ratio=ra)
dat=dat%>% arrange(quantity,ratio)
dat$quantity=as.character(dat$quantity)
dat$ratio=as.character(dat$ratio)

dat=data.frame(value=val, quantity=efs, ratio=ra)

f1 = ggplot(dat, aes(x=quantity, y=value, group=ratio, color=ratio))+
  geom_line(size=0.75,aes(y=jitter(value), linetype=ratio))+
  geom_point(size=1.5)+
  #geom_hline(yintercept=24, linetype='dotted')+
  #ylim(10,35)+  ##Power or  
  #ylim(50,300)+
  labs(y= "Sample size", x =  expression("Effect size "*theta) )+
  ggtitle(expression("k" * "=1.5, " * pi == 0))+#ggtitle("k=1.2, ")+
  scale_linetype_manual(values =c("dotdash", "longdash", "solid")) +
  scale_color_manual(values=c("#999999","#E69F00", "steelblue"))+  #, "#8DA0CB", "#E78AC3"
  #scale_shape_manual(values=c(0,2))+
  theme( plot.title = element_text(hjust=0, face = "bold", size=18),
       legend.title=element_blank(),
        legend.position = c(.6, .8),
        legend.direction="horizontal",
        #legend.justification = c("right", "top"),
        legend.text = element_text(colour="black", size=20),
        legend.key.size = unit(1.8, 'cm'),
        legend.key=element_rect(fill="white"),
        axis.title.x = element_text(color = "black", size = 20),
        axis.title.y = element_text(color = "black", size = 20),
        axis.text.x = element_text(size=18), 
        axis.text.y = element_text(size=18), 
        # Hide panel borders and remove grid lines
        panel.border = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        # Change axis line
        axis.line = element_line(colour = "black"),
        panel.background =   element_rect(fill = "white", colour = NA))


f1

```





#k=3, pi=0
```{r}
#lower back pain rho=0.3
n1_vec=c()
n2_vec=c()
n3_vec=c()
n4_vec=c()
n5_vec=c()
n6_vec=c()
n7_vec=c()
n8_vec=c()
n9_vec=c()
n10_vec=c()
n11_vec=c()
n12_vec=c()
n13_vec=c()
n14_vec=c()
n15_vec=c()
ind=seq(0.3,0.7, by=0.1)
for (i in ind) {
  res1=hybrid_one_stage(sigma1=20, sigma2=36, tau1=20, tau2=36,
                         theta=20*i,  mu_t=30, mu_c=20, pi=0, k=3,
                         c1=1200, c2=300,
                         r=1, lambda=1, 
                         alpha=0.025, beta=0.2,  
                         test="z_score", nsim=1, seed_number=13487)
  
  res2=hybrid_one_stage(sigma1=20, sigma2=36, tau1=20, tau2=36,
                         theta=20*i,  mu_t=30, mu_c=20, pi=0, k=3,
                         c1=1200, c2=300,
                         r=1.5, lambda=1, 
                         alpha=0.025, beta=0.2,  
                         test="z_score", nsim=1, seed_number=13487)
  
  res3=hybrid_one_stage(sigma1=20, sigma2=36, tau1=20, tau2=36,
                         theta=20*i,  mu_t=30, mu_c=20, pi=0, k=3,
                         c1=1200, c2=300,
                         r=2, lambda=1, 
                         alpha=0.025, beta=0.2,  
                         test="z_score", nsim=1, seed_number=13487)
  
  res4=hybrid_one_stage(sigma1=20, sigma2=36, tau1=20, tau2=36,
                         theta=20*i,  mu_t=30, mu_c=20, pi=0, k=3,
                         c1=1200, c2=300,
                         r=2.5, lambda=1, 
                         alpha=0.025, beta=0.2,  
                         test="z_score", nsim=1, seed_number=13487)
  
  res5=hybrid_one_stage(sigma1=20, sigma2=36, tau1=20, tau2=36,
                         theta=20*i,  mu_t=30, mu_c=20, pi=0, k=3,
                         c1=1200, c2=300,
                         r=3, lambda=1, 
                         alpha=0.025, beta=0.2,  
                         test="z_score", nsim=1, seed_number=13487)

  n1_vec=c(n1_vec,res1$n)
  n2_vec=c(n2_vec,res2$n)
  n3_vec=c(n3_vec,res3$n)
  n4_vec=c(n4_vec,res4$n)
  n5_vec=c(n5_vec,res5$n)

  
  
}

N_vec_cs_add = c(n1_vec, n3_vec,   n5_vec)

```





```{r}


val = N_vec_cs_add
efs = rep(seq(0.3,0.7,0.1),3)
ra = rep(c("r=1", "r=2", "r=3"), each=5)

dat=data.frame(value=val, quantity=efs, ratio=ra)
dat=dat%>% arrange(quantity,ratio)
dat$quantity=as.character(dat$quantity)
dat$ratio=as.character(dat$ratio)

dat=data.frame(value=val, quantity=efs, ratio=ra)

f2 = ggplot(dat, aes(x=quantity, y=value, group=ratio, color=ratio))+
  geom_line(size=0.75,aes(y=jitter(value), linetype=ratio))+
  geom_point(size=1.5)+
  #geom_hline(yintercept=24, linetype='dotted')+
  #ylim(10,35)+  ##Power or  
  #ylim(50,300)+
  labs(y= "Sample size", x = expression("Effect size "*theta))+
  ggtitle(expression("k" * "=3, " * pi == 0))+#ggtitle("k=1.8")+
  scale_linetype_manual(values =c("dotdash", "longdash", "solid")) +
  scale_color_manual(values=c("#999999","#E69F00", "steelblue"))+  #, "#8DA0CB", "#E78AC3"
  #scale_shape_manual(values=c(0,2))+
  theme(plot.title = element_text(hjust=0, face = "bold", size=18),
        legend.title=element_blank(),
        legend.position = c(.6, .8),
        legend.direction="horizontal",
        #legend.justification = c("right", "top"),
        legend.text = element_text(colour="black", size=20),
        legend.key.size = unit(1.8, 'cm'),
        legend.key=element_rect(fill="white"),
        axis.title.x = element_text(color = "black", size = 20),
        axis.title.y = element_text(color = "black", size = 20),
        axis.text.x = element_text(size=18), 
        axis.text.y = element_text(size=18), 
        # Hide panel borders and remove grid lines
        panel.border = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        # Change axis line
        axis.line = element_line(colour = "black"),
        panel.background =   element_rect(fill = "white", colour = NA))


f2


```






#k=1.5, pi=-0.2
```{r}
#lower back pain rho=0.3
n1_vec=c()
n2_vec=c()
n3_vec=c()
n4_vec=c()
n5_vec=c()
n6_vec=c()
n7_vec=c()
n8_vec=c()
n9_vec=c()
n10_vec=c()
n11_vec=c()
n12_vec=c()
n13_vec=c()
n14_vec=c()
n15_vec=c()
ind=seq(0.3,0.7, by=0.1)
for (i in ind) {
  res1=hybrid_one_stage(sigma1=20, sigma2=24, tau1=20, tau2=24,
                         theta=20*i,  mu_t=30, mu_c=20, pi=-0.2, k=1.5,
                         c1=1200, c2=300,
                         r=1, lambda=1, 
                         alpha=0.025, beta=0.2,  
                         test="z_score", nsim=1, seed_number=13487)
  
  res2=hybrid_one_stage(sigma1=20, sigma2=24, tau1=20, tau2=24,
                         theta=20*i,  mu_t=30, mu_c=20, pi=-0.2, k=1.5,
                         c1=1200, c2=300,
                         r=1.5, lambda=1, 
                         alpha=0.025, beta=0.2,  
                         test="z_score", nsim=1, seed_number=13487)
  
  res3=hybrid_one_stage(sigma1=20, sigma2=24, tau1=20, tau2=24,
                         theta=20*i,  mu_t=30, mu_c=20, pi=-0.2, k=1.5,
                         c1=1200, c2=300,
                         r=2, lambda=1, 
                         alpha=0.025, beta=0.2,  
                         test="z_score", nsim=1, seed_number=13487)
  
  res4=hybrid_one_stage(sigma1=20, sigma2=24, tau1=20, tau2=24,
                         theta=20*i,  mu_t=30, mu_c=20, pi=-0.2, k=1.5,
                         c1=1200, c2=300,
                         r=2.5, lambda=1, 
                         alpha=0.025, beta=0.2,  
                         test="z_score", nsim=1, seed_number=13487)
  
  res5=hybrid_one_stage(sigma1=20, sigma2=24, tau1=20, tau2=24,
                         theta=20*i,  mu_t=30, mu_c=20, pi=-0.2, k=1.5,
                         c1=1200, c2=300,
                         r=3, lambda=1, 
                         alpha=0.025, beta=0.2,  
                         test="z_score", nsim=1, seed_number=13487)

  n1_vec=c(n1_vec,res1$n)
  n2_vec=c(n2_vec,res2$n)
  n3_vec=c(n3_vec,res3$n)
  n4_vec=c(n4_vec,res4$n)
  n5_vec=c(n5_vec,res5$n)

  
  
}

N_vec_cs = c(n1_vec, n3_vec,   n5_vec)

```


```{r}


val = N_vec_cs
efs = rep(seq(0.3,0.7,0.1),3)
ra = rep(c("r=1", "r=2", "r=3"), each=5)

dat=data.frame(value=val, quantity=efs, ratio=ra)
dat=dat%>% arrange(quantity,ratio)
dat$quantity=as.character(dat$quantity)
dat$ratio=as.character(dat$ratio)

dat=data.frame(value=val, quantity=efs, ratio=ra)

f3 = ggplot(dat, aes(x=quantity, y=value, group=ratio, color=ratio))+
  geom_line(size=0.75,aes(y=jitter(value), linetype=ratio))+
  geom_point(size=1.5)+
  #geom_hline(yintercept=24, linetype='dotted')+
  #ylim(10,35)+  ##Power or  
  #ylim(50,300)+
  labs(y= "Sample size", x =  expression("Effect size "*theta) )+
  ggtitle(expression("k" * "=1.5, " * pi == -0.2))+
  #ggtitle("k=1.2")+
  scale_linetype_manual(values =c("dotdash", "longdash", "solid")) +
  scale_color_manual(values=c("#999999","#E69F00", "steelblue"))+  #, "#8DA0CB", "#E78AC3"
  #scale_shape_manual(values=c(0,2))+
  theme( plot.title = element_text(hjust=0, face = "bold", size=18),
       legend.title=element_blank(),
        legend.position = c(.6, .8),
        legend.direction="horizontal",
        #legend.justification = c("right", "top"),
        legend.text = element_text(colour="black", size=20),
        legend.key.size = unit(1.8, 'cm'),
        legend.key=element_rect(fill="white"),
        axis.title.x = element_text(color = "black", size = 20),
        axis.title.y = element_text(color = "black", size = 20),
        axis.text.x = element_text(size=18), 
        axis.text.y = element_text(size=18), 
        # Hide panel borders and remove grid lines
        panel.border = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        # Change axis line
        axis.line = element_line(colour = "black"),
        panel.background =   element_rect(fill = "white", colour = NA))


f3

```





#k=3 pi=0.8
```{r}
#lower back pain rho=0.3
n1_vec=c()
n2_vec=c()
n3_vec=c()
n4_vec=c()
n5_vec=c()
n6_vec=c()
n7_vec=c()
n8_vec=c()
n9_vec=c()
n10_vec=c()
n11_vec=c()
n12_vec=c()
n13_vec=c()
n14_vec=c()
n15_vec=c()
ind=seq(0.3,0.7, by=0.1)
for (i in ind) {
  res1=hybrid_one_stage(sigma1=20, sigma2=36, tau1=20, tau2=36,
                         theta=20*i,  mu_t=30, mu_c=20, pi=-0.2, k=3,
                         c1=1200, c2=300,
                         r=1, lambda=1, 
                         alpha=0.025, beta=0.2,  
                         test="z_score", nsim=1, seed_number=13487)
  
  res2=hybrid_one_stage(sigma1=20, sigma2=36, tau1=20, tau2=36,
                         theta=20*i,  mu_t=30, mu_c=20, pi=-0.2, k=3,
                         c1=1200, c2=300,
                         r=1.5, lambda=1, 
                         alpha=0.025, beta=0.2,  
                         test="z_score", nsim=1, seed_number=13487)
  
  res3=hybrid_one_stage(sigma1=20, sigma2=36, tau1=20, tau2=36,
                         theta=20*i,  mu_t=30, mu_c=20, pi=-0.2, k=3,
                         c1=1200, c2=300,
                         r=2, lambda=1, 
                         alpha=0.025, beta=0.2,  
                         test="z_score", nsim=1, seed_number=13487)
  
  res4=hybrid_one_stage(sigma1=20, sigma2=36, tau1=20, tau2=36,
                         theta=20*i,  mu_t=30, mu_c=20, pi=-0.2, k=3,
                         c1=1200, c2=300,
                         r=2.5, lambda=1, 
                         alpha=0.025, beta=0.2,  
                         test="z_score", nsim=1, seed_number=13487)
  
  res5=hybrid_one_stage(sigma1=20, sigma2=36, tau1=20, tau2=36,
                         theta=20*i,  mu_t=30, mu_c=20, pi=-0.2, k=3,
                         c1=1200, c2=300,
                         r=3, lambda=1, 
                         alpha=0.025, beta=0.2,  
                         test="z_score", nsim=1, seed_number=13487)

  n1_vec=c(n1_vec,res1$n)
  n2_vec=c(n2_vec,res2$n)
  n3_vec=c(n3_vec,res3$n)
  n4_vec=c(n4_vec,res4$n)
  n5_vec=c(n5_vec,res5$n)

  
  
}

N_vec_cs_add = c(n1_vec, n3_vec,   n5_vec)

```





```{r}


val = N_vec_cs_add
efs = rep(seq(0.3,0.7,0.1),3)
ra = rep(c("r=1", "r=2", "r=3"), each=5)

dat=data.frame(value=val, quantity=efs, ratio=ra)
dat=dat%>% arrange(quantity,ratio)
dat$quantity=as.character(dat$quantity)
dat$ratio=as.character(dat$ratio)

dat=data.frame(value=val, quantity=efs, ratio=ra)

f4 = ggplot(dat, aes(x=quantity, y=value, group=ratio, color=ratio))+
  geom_line(size=0.75,aes(y=jitter(value), linetype=ratio))+
  geom_point(size=1.5)+
  #geom_hline(yintercept=24, linetype='dotted')+
  #ylim(10,35)+  ##Power or  
  #ylim(50,300)+
  labs(y= "Sample size", x = expression("Effect size "*theta))+
  ggtitle(expression("k" * "=3, " * pi == -0.2))+#ggtitle("k=1.8")+
  scale_linetype_manual(values =c("dotdash", "longdash", "solid")) +
  scale_color_manual(values=c("#999999","#E69F00", "steelblue"))+  #, "#8DA0CB", "#E78AC3"
  #scale_shape_manual(values=c(0,2))+
  theme(plot.title = element_text(hjust=0, face = "bold", size=18),
        legend.title=element_blank(),
        legend.position = c(.6, .8),
        legend.direction="horizontal",
        #legend.justification = c("right", "top"),
        legend.text = element_text(colour="black", size=20),
        legend.key.size = unit(1.8, 'cm'),
        legend.key=element_rect(fill="white"),
        axis.title.x = element_text(color = "black", size = 20),
        axis.title.y = element_text(color = "black", size = 20),
        axis.text.x = element_text(size=18), 
        axis.text.y = element_text(size=18), 
        # Hide panel borders and remove grid lines
        panel.border = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        # Change axis line
        axis.line = element_line(colour = "black"),
        panel.background =   element_rect(fill = "white", colour = NA))


f4


```






#combined figure 2:

```{r}
pdf("cs_sample_size_combined.pdf",width=12, height = 5)
ggarrange(f1,f2,f3,f4,ncol = 2, nrow = 2,labels = c("A", "B", "C", "D"))
dev.off()

#ggsave(
#  "Feng_Tian_Figure_2_sample_size_change1.pdf",
#  plot = last_plot(),
#  device = "pdf",  #tiff
#  scale = 1,
#  width = 12,
#  height = 5,
  #units = c("in", "cm", "mm", "px"),
#  dpi = 1500,
  #limitsize = TRUE,
  #bg = NULL,
#)


ggsave(
  "Feng_Tian_Figure_2_sample_size_change1.png",
  plot = last_plot(),
  device = "png",  #tiff
  scale = 1,
  width = 12,
  height = 9,
  #units = c("in", "cm", "mm", "px"),
  dpi = 1500,
  #limitsize = TRUE,
  #bg = NULL,
)

```












